// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANw5BoZvyQr0pOmiX0FDfxU0l-ptpniJc',
    appId: '1:522462075867:web:c803d201ff1274cd81a5fe',
    messagingSenderId: '522462075867',
    projectId: 'winkle-c8e32',
    authDomain: 'winkle-c8e32.firebaseapp.com',
    storageBucket: 'winkle-c8e32.appspot.com',
    measurementId: 'G-WT9ZGNP9RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8gy5EQ6AL4ZnucX_TOpmvc6noubQR0CU',
    appId: '1:522462075867:android:acc76c408b7e785d81a5fe',
    messagingSenderId: '522462075867',
    projectId: 'winkle-c8e32',
    storageBucket: 'winkle-c8e32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMqO_yQTnauFvju7u3EIC7XgbDr4ZxOOU',
    appId: '1:522462075867:ios:605f83d0ae45c99b81a5fe',
    messagingSenderId: '522462075867',
    projectId: 'winkle-c8e32',
    storageBucket: 'winkle-c8e32.appspot.com',
    iosBundleId: 'alperen.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMqO_yQTnauFvju7u3EIC7XgbDr4ZxOOU',
    appId: '1:522462075867:ios:605f83d0ae45c99b81a5fe',
    messagingSenderId: '522462075867',
    projectId: 'winkle-c8e32',
    storageBucket: 'winkle-c8e32.appspot.com',
    iosBundleId: 'alperen.example.todo',
  );
}
